#ifndef STARFLEET_COMMAND_PREDEFINEDCOLOURS_HPP
#define STARFLEET_COMMAND_PREDEFINEDCOLOURS_HPP
#include "SFML/Graphics/Color.hpp"

struct PredefinedColours
{
    sf::Color LIGHTBLUE {153, 210, 242};
    sf::Color LIGHTGREEN {91, 239, 170};
    sf::Color LIGHTRED {253, 103, 100};
};

#endif //STARFLEET_COMMAND_PREDEFINEDCOLOURS_HPP
